apiVersion: v2
name: vsphere-csi
description: A Helm chart for vsphere-csi
home: https://github.com/CloudNomster/helm-vsphere-csi
type: application
version: 0.1.0
deprecated: false

dependencies:
  - name: vsphere-csi
    version: 3.7.0
    repository: https://vsphere-tmm.github.io/helm-charts

    values: |
      vsphere-csi:
        global:
          config:
            vcenter:
              <path:k8s/data/vsphere#hostname>:
                server: <path:k8s/data/vsphere#hostname>
                user: <path:k8s/data/vsphere#user>
                password: <path:k8s/data/vsphere#pass>
                datacenters:
                  - GeekHouse
                secretName: cpi-engineering-secret
                secretNamespace: kube-system